//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditerskaya_Nikushina
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFullInfo
    {
        public int Order_number { get; set; }
        public System.DateTime Date { get; set; }
        public string Client { get; set; }
        public string Status { get; set; }
        public string Payment_method { get; set; }
        public string Employee { get; set; }
        public string Address { get; set; }
    }
}
