//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditerskaya_Nikushina
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseAssortment
    {
        public int Warehouse_ID { get; set; }
        public string Product { get; set; }
        public int Expiry_date { get; set; }
        public string Cell { get; set; }
        public int Quantity { get; set; }
    }
}
